{{- if and .Values.rbac.create (eq .Values.rbac.scope "cluster") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pod-deletion-cost-controller.fullname" . }}
  labels:
    {{- include "pod-deletion-cost-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pod-deletion-cost-controller.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pod-deletion-cost-controller.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
