{{- if and .Values.rbac.create (eq .Values.rbac.scope "cluster") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pod-deletion-cost-controller.fullname" . }}
  labels:
    {{- include "pod-deletion-cost-controller.labels" . | nindent 4 }}
rules:
  {{- include "pod-deletion-cost-controller.rules" . | nindent 2 }}
{{- end }}
